<?php
namespace app\controller\admin;

use app\model\Task;
use app\model\TaskRecord;
use app\model\Client;
use app\model\Image;
use app\model\UnattendTemplate;
use app\model\SoftwareTemplate;
use app\model\Software;
use think\facade\Db;

class TaskController extends BaseController
{
    public function index()
    {
        $keyword = input('keyword');
        $status = input('status');
        $clientId = input('client_id');
        $startDate = input('start_date');
        $endDate = input('end_date');

        $query = Task::order('id', 'desc');

        if ($keyword) {
            $query->where('task_no', 'like', '%' . $keyword . '%');
        }
        if ($status !== null && $status !== '') {
            $query->where('status', $status);
        }
        if ($clientId) {
            $query->where('client_id', $clientId);
        }
        if ($startDate) {
            $query->where('created_at', '>=', $startDate);
        }
        if ($endDate) {
            $query->where('created_at', '<=', $endDate . ' 23:59:59');
        }

        // 逐条附加智能判定：停滞任务 / 客户端在线状态（仅供展示，不落库）
        $page = input("page", 1);
        $limit = input("limit", input("pageSize", 20));
        $list = $query->paginate($limit, false, ["page" => $page]);
        $now = time();
        $clientIds = array_filter(array_column($list->items(), "client_id"));
        $clientOnline = [];
        if ($clientIds) {
            $rows = Client::whereIn("id", $clientIds)->field("id,status,last_heartbeat")->select()->toArray();
            foreach ($rows as $r) {
                $hb = $r["last_heartbeat"] ? strtotime($r["last_heartbeat"]) : 0;
                $clientOnline[$r["id"]] = $r["status"] === "approved" && ($now - $hb) <= 90;
            }
        }
        foreach ($list->items() as $item) {
            $item->is_stalled = false;
            $item->stalled_reason = "";
            $ref = $item->status === "running" ? $item->updated_at : $item->created_at;
            $age = $ref ? $now - strtotime($ref) : 0;
            if ($item->status === "running" && $age > 1200) {
                $item->is_stalled = true;
                $item->stalled_reason = "执行中超过 20 分钟无进度更新";
            } elseif ($item->status === "waiting" && $age > 86400) {
                $item->is_stalled = true;
                $item->stalled_reason = "等待 PE 执行超过 24 小时";
            }
            $item->client_online = $clientOnline[$item->client_id] ?? false;
        }
        return $this->success([
            "list" => $list->items(),
            "total" => $list->total(),
            "page" => (int) $page,
            "limit" => (int) $limit,
            "pages" => $list->lastPage(),
        ]);
    }

    public function detail($id)
    {
        $task = Task::with(['client', 'image', 'records'])->find($id);
        if (!$task) {
            return $this->error('task_not_found');
        }
        return $this->success($task);
    }

    /**
     * 获取任务关联的无人值守 XML（WinPE 部署完成后写入 Panther\unattend.xml）
     * 优先级：任务指定的模板 → 默认模板 → 返回空
     */
    public function unattend($id)
    {
        $task = Task::find($id);
        if (!$task) {
            return $this->error('task_not_found');
        }

        $xml = '';
        $templateId = $task->unattend_template_id;
        $options = json_decode($task->options ?? '', true);
        if (!$templateId && is_array($options) && !empty($options['unattend_template_id'])) {
            $templateId = $options['unattend_template_id'];
        }

        $template = null;
        if ($templateId) {
            $template = UnattendTemplate::find($templateId);
        }
        if (!$template) {
            $template = UnattendTemplate::where('is_default', 1)->find();
        }

        if ($template) {
            $xml = $template->xml_content
                ?: self::renderXmlFromTemplate($template);
        }

        return $this->success([
            'task_id' => $task->id,
            'task_no' => $task->task_no,
            'template_id' => $template ? $template->id : null,
            'template_name' => $template ? $template->name : null,
            'xml' => $xml,
        ]);
    }

    /**
     * 生成首次登录脚本（SetupComplete.cmd）：WinPE 部署完成后写入 C:\Windows\Setup\Scripts\SetupComplete.cmd。
     * 服务端按任务选项智能生成：软件安装（按软件模板清单，静默安装，文件存在才执行）+ 系统优化（注册表/电源计划）。
     */
    public function firstLogon($id)
    {
        $task = Task::find($id);
        if (!$task) {
            return $this->error('task_not_found');
        }

        $options = json_decode($task->options ?? '', true) ?: [];
        $installSoftware = !empty($options['install_software']);
        $optimize = array_key_exists('optimize', $options) ? (bool) $options['optimize'] : true;
        $optimizePlan = $options['optimize_plan'] ?? 'performance';

        $lines = [];
        $lines[] = '@echo off';
        $lines[] = 'rem ZS Installer - first logon script (generated by server for task ' . $task->task_no . ')';
        $lines[] = 'set "LOG=C:\ZS_Setup\first_logon.log"';
        $lines[] = 'if not exist "C:\ZS_Setup" mkdir "C:\ZS_Setup"';
        $lines[] = 'echo [%date% %time%] first-logon start >> "%LOG%"';

        // 软件安装（按软件模板清单，静默安装；安装包缺失时安全跳过）
        if ($installSoftware) {
            $softwareTemplateId = $options['software_template_id'] ?? null;
            $softwareList = [];
            if ($softwareTemplateId) {
                $tmpl = SoftwareTemplate::find($softwareTemplateId);
                if ($tmpl) {
                    $raw = $tmpl->software_ids;
                    $ids = is_array($raw) ? $raw : (json_decode((string) $raw, true) ?: array_filter(array_map('trim', explode(',', (string) $raw))));
                    if ($ids) {
                        $softwareList = Software::whereIn('id', array_map('intval', $ids))
                            ->where('status', 1)->order('sort', 'asc')->select()->toArray();
                    }
                }
            }
            $lines[] = 'echo ---- install software ---- >> "%LOG%"';
            foreach ($softwareList as $sw) {
                $fileUrl = (string) ($sw['file_url'] ?? '');
                $path = (string) parse_url($fileUrl, PHP_URL_PATH);
                $fileName = $path ? basename($path) : basename($fileUrl);
                if ($fileName === '') continue;
                $params = trim((string) ($sw['install_params'] ?? ''));
                if (!empty($sw['silent_install']) && $params === '') $params = '/S';
                $lines[] = 'if exist "C:\ZS_Setup\Software\\' . $fileName . '" (';
                $lines[] = '  echo installing ' . $sw['name'] . ' >> "%LOG%"';
                $lines[] = '  start /wait "" "C:\ZS_Setup\Software\\' . $fileName . '" ' . $params . ' >> "%LOG%" 2>&1';
                $lines[] = ') else (';
                $lines[] = '  echo skip ' . $sw['name'] . ' (package missing) >> "%LOG%"';
                $lines[] = ')';
            }
        }

        // 系统优化（注册表 + 电源计划）
        if ($optimize) {
            $lines[] = 'echo ---- system optimize (' . $optimizePlan . ') ---- >> "%LOG%"';
            $lines[] = 'reg add "HKCU\Control Panel\Desktop" /v MenuShowDelay /t REG_SZ /d 0 /f >> "%LOG%" 2>&1';
            $lines[] = 'reg add "HKCU\Control Panel\Desktop" /v AutoEndTasks /t REG_SZ /d 1 /f >> "%LOG%" 2>&1';
            $lines[] = 'reg add "HKCU\Control Panel\Desktop" /v WaitToKillAppTimeout /t REG_SZ /d 5000 /f >> "%LOG%" 2>&1';
            $lines[] = 'reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v HideFileExt /t REG_DWORD /d 0 /f >> "%LOG%" 2>&1';
            $lines[] = 'reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v ShowSuperHidden /t REG_DWORD /d 1 /f >> "%LOG%" 2>&1';
            $lines[] = 'reg add "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" /v LargeSystemCache /t REG_DWORD /d 1 /f >> "%LOG%" 2>&1';
            $lines[] = 'reg add "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" /v DisablePagingExecutive /t REG_DWORD /d 1 /f >> "%LOG%" 2>&1';
            if ($optimizePlan === 'performance') {
                $lines[] = 'powercfg /setactive SCHEME_MIN >> "%LOG%" 2>&1';
            } else {
                $lines[] = 'powercfg /setactive SCHEME_BALANCED >> "%LOG%" 2>&1';
            }
        }

        // 完成后清理自身（不留残留）
        $lines[] = 'echo [%date% %time%] first-logon done >> "%LOG%"';
        $lines[] = 'del /q "%~f0" >> "%LOG%" 2>&1';

        return $this->success([
            'task_id' => $task->id,
            'task_no' => $task->task_no,
            'cmd' => implode("\r\n", $lines),
        ]);
    }

    private static function renderXmlFromTemplate($template)
    {
        return UnattendController::renderXml($template->template_type, $template->config);
    }

    public function create()
    {
        // status 初始状态：Windows 端下单传 waiting（等待 PE 执行）；PE 端/后台默认 pending
        $status = input('status', '');
        if ($status === '' || !in_array($status, ['pending', 'waiting'])) {
            $status = 'pending';
        }

        // options 契约收全（含默认值），供 PE 端完整读取
        $options = $this->buildOptions();
        $optionsArr = json_decode($options, true) ?: [];

        // 无人值守默认模板兜底：开启无人值守但未指定模板 → 自动使用默认模板（后台更智能）
        $unattendTemplateId = input('unattend_template_id') ?: input('template_id');
        if (!$unattendTemplateId && !empty($optionsArr['unattended'])) {
            $defaultTemplate = UnattendTemplate::where('is_default', 1)->find();
            if ($defaultTemplate) {
                $unattendTemplateId = $defaultTemplate->id;
                $optionsArr['unattend_template_id'] = $defaultTemplate->id;
                $options = json_encode($optionsArr, JSON_UNESCAPED_UNICODE);
            }
        }

        $data = [
            'task_no' => $this->generateTaskNo(),
            'client_id' => input('client_id') ?: null,
            'image_id' => input('image_id'),
            'unattend_template_id' => $unattendTemplateId,
            'target_disk_index' => (int) input('target_disk_index', 0),
            'target_partition' => input('target_partition', 'C:'),
            'partition_scheme' => in_array(input('partition_scheme'), ['auto', 'custom', 'keep'])
                ? input('partition_scheme') : 'auto',
            'options' => $options,
            'status' => $status,
            'created_by' => $this->userId,
        ];

        if (empty($data['image_id'])) {
            return $this->error('param_error', '镜像ID不能为空');
        }
        if (!Image::find($data['image_id'])) {
            return $this->error('image_not_found', '镜像不存在');
        }
        if ($data['client_id']) {
            $client = Client::find($data['client_id']);
            if (!$client) {
                return $this->error('client_not_found', '客户端不存在');
            }
            if ($client->status !== 'approved') {
                return $this->error('auth_client_pending', '客户端未通过审核，无法派发任务');
            }
        }

        $task = Task::create($data);
        return $this->success($task, '创建成功');
    }

    /**
     * 生成任务编号：YYYYMMDDHHmmss + 6位随机数
     */
    private function generateTaskNo()
    {
        return date('YmdHis') . str_pad((string) mt_rand(0, 999999), 6, '0', STR_PAD_LEFT);
    }

    /**
     * options 列存储 JSON：与「全功能流程闭环清单」第 7.2 节契约对齐，
     * 缺失字段自动补默认值，保证双端读取到完整选项。
     */
    private function buildOptions()
    {
        $defaults = [
            'type' => 'install',
            'auto_partition' => true,
            'auto_repair_boot' => true,
            'auto_inject_drivers' => false,
            'unattended' => false,
            'install_software' => false,
            'optimize' => true,
            'backup_data' => false,
            'image_index' => 1,
            'unattend_template_id' => null,
            'software_template_id' => null,
            'driver_package' => 'auto',
            'optimize_plan' => 'performance',
            'backup_location' => 'auto',
        ];

        $options = input('options');
        if (is_string($options)) {
            $decoded = json_decode($options, true);
            if (is_array($decoded)) {
                return json_encode(array_merge($defaults, $decoded), JSON_UNESCAPED_UNICODE);
            }
        }
        if (is_array($options)) {
            return json_encode(array_merge($defaults, $options), JSON_UNESCAPED_UNICODE);
        }
        $params = input('params/a', []);
        if ($params) {
            return json_encode(array_merge($defaults, $params), JSON_UNESCAPED_UNICODE);
        }
        $type = input('type');
        if ($type) {
            return json_encode(array_merge($defaults, ['type' => $type]), JSON_UNESCAPED_UNICODE);
        }
        return json_encode($defaults, JSON_UNESCAPED_UNICODE);
    }

    public function cancel($id)
    {
        $task = Task::find($id);
        if (!$task) {
            return $this->error('task_not_found');
        }

        if (!in_array($task->status, ['pending', 'waiting', 'running'])) {
            return $this->error('task_cancel_not_allowed', '当前状态不允许取消');
        }

        $task->status = 'cancelled';
        $task->cancelled_at = date('Y-m-d H:i:s');
        $task->cancelled_by = $this->userId;
        $task->save();

        return $this->success($task, '已取消');
    }

    public function retry($id)
    {
        $task = Task::find($id);
        if (!$task) {
            return $this->error('task_not_found');
        }

        if (!in_array($task->status, ['failed', 'cancelled'])) {
            return $this->error('task_status_error', '当前状态不允许重试');
        }

        $task->status = 'pending';
        $task->retry_count = $task->retry_count + 1;
        $task->save();

        return $this->success($task, '已加入重试队列');
    }

    public function pause($id)
    {
        $task = Task::find($id);
        if (!$task) {
            return $this->error('task_not_found');
        }

        if ($task->status !== 'running') {
            return $this->error('task_status_error', '只有运行中的任务可以暂停');
        }

        $task->status = 'paused';
        $task->save();

        return $this->success($task, '已暂停');
    }

    public function resume($id)
    {
        $task = Task::find($id);
        if (!$task) {
            return $this->error('task_not_found');
        }

        if ($task->status !== 'paused') {
            return $this->error('task_status_error', '只有暂停的任务可以恢复');
        }

        $task->status = 'running';
        $task->save();

        return $this->success($task, '已恢复');
    }

    public function logs($id)
    {
        $task = Task::find($id);
        if (!$task) {
            return $this->error('task_not_found');
        }

        $query = TaskRecord::where('task_id', $id)->order('id', 'asc');
        return $this->paginate($query);
    }

    public function progress($id)
    {
        $task = Task::find($id);
        if (!$task) {
            return $this->error('task_not_found');
        }
        $progress = input('progress/d', 0);
        $message = input('message', '');
        $stepName = input('step_name', '');
        // 客户端可上报状态：running/completed/failed
        $reportStatus = input('status', '');
        if ($progress < 0 || $progress > 100) {
            return $this->error('param_error', '进度值必须在0-100之间');
        }

        $recordStatus = 'running';
        $task->progress = $progress;

        if ($reportStatus === 'failed') {
            $task->status = 'failed';
            $task->error_message = $message ?: '任务执行失败';
            $task->completed_at = date('Y-m-d H:i:s');
            $recordStatus = 'failed';
        } elseif ($reportStatus === 'completed' || $progress >= 100) {
            $task->status = 'completed';
            $task->completed_at = date('Y-m-d H:i:s');
            $task->progress = 100;
            $recordStatus = 'completed';
        } elseif (in_array($task->status, ['pending', 'waiting']) && $reportStatus === 'running') {
            $task->status = 'running';
            $task->started_at = date('Y-m-d H:i:s');
        }

        // 计算耗时（秒）
        if ($task->started_at && in_array($task->status, ['completed', 'failed', 'cancelled'])) {
            $task->duration = max(0, strtotime($task->completed_at ?: date('Y-m-d H:i:s')) - strtotime($task->started_at));
        }

        $task->save();

        if ($message || $stepName) {
            TaskRecord::create([
                'task_id' => $id,
                'step_name' => $stepName ?: '进度更新',
                'action' => 'progress',
                'status' => $recordStatus,
                'progress' => $progress,
                'message' => $message,
                'started_at' => date('Y-m-d H:i:s'),
                'completed_at' => in_array($recordStatus, ['completed', 'failed']) ? date('Y-m-d H:i:s') : null,
            ]);
        }
        return $this->success(['progress' => $progress, 'status' => $task->status], '进度已更新');
    }

    public function template()
    {
        return $this->success([
            'types' => ['install', 'usb', 'repair', 'other'],
            'statuses' => ['pending', 'waiting', 'running', 'paused', 'completed', 'failed', 'cancelled'],
            'partition_schemes' => ['auto', 'custom', 'keep'],
            'priorities' => [0 => '低', 1 => '中', 2 => '高', 3 => '紧急'],
        ]);
    }
}