<?php
return [
    "success"               => ["code" => 0,     "message" => "操作成功"],
    "error"                 => ["code" => 1000,  "message" => "系统错误"],
    "param_error"           => ["code" => 1001,  "message" => "参数错误"],
    "not_found"             => ["code" => 1002,  "message" => "资源不存在"],
    "method_not_allowed"    => ["code" => 1003,  "message" => "请求方法不允许"],
    "request_too_frequent"  => ["code" => 1004,  "message" => "请求过于频繁"],
    "file_upload_failed"    => ["code" => 2000,  "message" => "文件上传失败"],
    "file_type_not_allowed" => ["code" => 2001,  "message" => "文件类型不允许"],
    "file_too_large"        => ["code" => 2002,  "message" => "文件大小超出限制"],
    "file_not_found"        => ["code" => 2003,  "message" => "文件不存在"],
    "file_hash_mismatch"    => ["code" => 2004,  "message" => "文件哈希校验失败"],
    "file_exists"           => ["code" => 2005,  "message" => "文件已存在"],
    "auth_failed"           => ["code" => 3000,  "message" => "认证失败"],
    "auth_token_expired"    => ["code" => 3001,  "message" => "Token 已过期"],
    "auth_token_invalid"    => ["code" => 3002,  "message" => "Token 无效"],
    "auth_permission_denied" => ["code" => 3003, "message" => "权限不足"],
    "auth_login_required"   => ["code" => 3004,  "message" => "请先登录"],
    "auth_account_blocked"  => ["code" => 3005,  "message" => "账号已被禁用"],
    "auth_client_offline"   => ["code" => 3006,  "message" => "客户端离线"],
    "auth_client_pending"   => ["code" => 3007,  "message" => "客户端待审核"],
    "client_not_registered" => ["code" => 3008,  "message" => "客户端尚未注册"],
    "client_not_found"      => ["code" => 3009,  "message" => "客户端不存在"],
    "template_not_found"    => ["code" => 3010,  "message" => "无人值守模板不存在"],
    "task_not_found"        => ["code" => 4000,  "message" => "任务不存在"],
    "task_status_error"     => ["code" => 4001,  "message" => "任务状态错误"],
    "task_already_running"  => ["code" => 4002,  "message" => "任务正在运行中"],
    "task_create_failed"    => ["code" => 4003,  "message" => "任务创建失败"],
    "task_cancel_not_allowed" => ["code" => 4004, "message" => "当前状态不允许取消"],
    "image_not_found"       => ["code" => 5000,  "message" => "镜像不存在"],
    "image_format_error"    => ["code" => 5001,  "message" => "镜像格式不支持"],
    "image_download_failed" => ["code" => 5002,  "message" => "镜像下载失败"],
    "image_downloading"     => ["code" => 5003,  "message" => "镜像正在下载中"],
    "image_verify_failed"   => ["code" => 5004,  "message" => "镜像校验失败"],
    "db_error"              => ["code" => 6000,  "message" => "数据库错误"],
    "cache_error"           => ["code" => 6001,  "message" => "缓存错误"],
    "redis_unavailable"     => ["code" => 6002,  "message" => "Redis 不可用"],
    "storage_full"          => ["code" => 6003,  "message" => "存储空间不足"],
    "backup_failed"         => ["code" => 6004,  "message" => "备份失败"],
    "restore_failed"        => ["code" => 6005,  "message" => "恢复失败"],
];
