<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>IsoLogicTest</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Windows_Client">
      <HintPath>..\publish\Windows_Client\Windows_Client.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
