<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PeIsoBuild</AssemblyName>
    <StartupObject>Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Windows_Client\Services\IsoBuilder.cs" Link="Services\IsoBuilder.cs" />
    <Compile Include="..\Windows_Client\Services\EfiSysGenerator.cs" Link="Services\EfiSysGenerator.cs" />
  </ItemGroup>
</Project>
